### PR TITLE
setup.py: Upgrade to markupsafe==3.0.2

### PR DESCRIPTION
**Pull request by cclauss**
```diff
-        # Pin markupsafe because of
-        # https://github.com/pallets/jinja/issues/1585
-        "markupsafe==2.0.1",
+        "markupsafe==3.0.2",
```
https://pypi.org/project/MarkupSafe

https://github.com/pyodide/sphinx-js-fork/pulls/cclauss

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks!

**Comment by hoodmane** [comment]
Why didn't the CI run?

**Comment by cclauss** [comment]
I am not a maintainer of this repo so my FIRST pr’s workflow run must be approved by a maintainer.

**Comment by hoodmane** [comment]
I don't see a button to approve it...

**Comment by hoodmane** [comment]
Ah I found "Switch back to classic merge experience" and it's here.

**Comment by hoodmane** [comment]
Looks like I have to bump upload-artifact/download-artifact versions first.

**Comment by hoodmane** [comment]
Okay, I updated the upload-artifacts version. Can you merge master on all your prs?

**Comment by hoodmane** [comment]
Thanks @cclauss!

**Comment by cclauss** [comment]
> Can you merge master on all your prs?

Done.  https://github.com/pyodide/sphinx-js-fork/pulls/cclauss

**Pull request merged**
