### PR TITLE
Add test result reports

### PR DESCRIPTION
**Pull request by hoodmane**

### CODE REVIEW

**Comment by ryanking13** [comment]
Thanks for the work @hoodmane!

About the permission issue, I guess the recommended way is [to create a separate `workflow_run` actions](https://github.com/dorny/test-reporter#recommended-setup-for-public-repositories), which has a write permission.

**Comment by hoodmane** [comment]
Would you mind fixing it for me? I guess we'll have to merge master first.

**Comment by ryanking13** [comment]
Sure, I'll try.

**Comment by hoodmane** [comment]
So beautiful, thanks @ryanking13!

**Pull request merged**
