### PR TITLE
Use Pydantic V2

### PR DESCRIPTION
**Pull request by ryanking13**
Bump pydantic version to v2. I tried to update the pydantic version [following the migration guide](https://docs.pydantic.dev/dev/migration/), but after migration, the tests started to blow up.

So this PR updates the pydantic version but replaces all `import pydantic` to `import pydantic.v1` so everything works as before.

### CODE REVIEW

**Comment by ryanking13** [comment]
```
FAILED tests/test_build_ts/test_build_ts.py::TestTextBuilder::test_example - AssertionError: assert 'exampleFunct...hing python\n' == 'exampleFunct...hing python\n'
  
  Skipping 60 identical leading characters in diff, use -v to show
  -   Example: This is another example.
  +   Example:
    
          Something python
```

It looks like this test is failing in the main branch, too...

**Comment by ryanking13** [comment]
Pinning typedoc version to 0.25.0 (latest version is 0.25.13) seems to work.

**Comment by hoodmane** [comment]
I fixed the test failures #114

**Comment by ryanking13** [comment]
> I fixed the test failures https://github.com/pyodide/sphinx-js-fork/pull/114

Great, thanks! Reverted pinning typedoc version.

**Pull request closed without merging**
